UPDATE stores SET dealer_category = 'A+' WHERE name = 'AGRAWAL KRUSHI KENDRA POULDOWNA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'AJIT PATLE';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'AMBULE KK CHANDORI';
UPDATE stores SET dealer_category = 'A' WHERE name = 'AMIRA K.K DONGARGAON (KATTIPAR)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'AMOL K.K DHAPEWADA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'ANAND KRUSHI KENDRA FULCHUR';
UPDATE stores SET dealer_category = 'D' WHERE name = 'ANINDRA KRUSHI KENDRA KATURLI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Anju Bai';
UPDATE stores SET dealer_category = 'A' WHERE name = 'ANNAPURNA KK BOTHLI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'ANSH KRUSHI KENDRA CHUTIYA';
UPDATE stores SET dealer_category = 'C' WHERE name = 'ARCHANA K.K SAKRITOLA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'ARCHANA KK KATURLI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'ARTI KRUSHI KENDRA TEDWA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'ARYA KK DATORA (GONDIA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'ASATI KRUSHI KENDRA BORKANHAR';
UPDATE stores SET dealer_category = 'D' WHERE name = 'ASHISH KK KHADIPAR (MURDOLI)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'ASHISH KK PANJRA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Ashok Rahele';
UPDATE stores SET dealer_category = 'B' WHERE name = 'AYUSH KRUSHI KENDRA WARAD';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Babita Bai';
UPDATE stores SET dealer_category = 'A' WHERE name = 'BAGDE KK TUMSAR';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'BAHUBALI KRUSHI KENDRA CHICHGARH (DEORI)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'BAITHWAR KK JHALIYA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BALAJI K.K KUMBARTOLI (AMGAON)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BALIRAJA KK SARANDI (TIRODA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'BALIRAJA KRUSHI KENDRA BAMNI (KHADKI)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'BALIRAJA KRUSHI KENDRA KURADI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BALIRAJA KRUSHI KENDRA THANA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'BAVANTHADE KK KATANGINAKA (GONDIA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BAVANTHADE KRUSHI KENDRA MAHARITOLA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'BHAGYASHREE KRUSHI KENDRA KHOLGARH';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BHANUPRATAP';
UPDATE stores SET dealer_category = 'D' WHERE name = 'BHARAT KK MAKKATOLA (SAKRITOLA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BISEN SIR (THANA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BORKER KK SUKDI (TIRORA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'BRAMHANKAR KRUSHI KENDRA TEDHA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BSH BRS AGRO NAGPUR';
UPDATE stores SET dealer_category = 'B' WHERE name = 'BSH BRS CHEMICALS SALE ACCOUNT';
UPDATE stores SET dealer_category = 'D' WHERE name = 'CHIKLONDE KRUSHI KENDRA NAGRA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'CHIRAG KRUSHI KENDRA KAVLEWADA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'CHULBAND F.P.O GATEGAON (GOREGAON)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'DAHARIA KRUSHI KENDRA DONGARGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'DAKHNE KK SUKDI (TIRORA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'DAKSH KK AMBHORA (GONDAI)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'DASHARIA KRUSHI KENDRA GOWARITOLA (SALEK';
UPDATE stores SET dealer_category = 'A' WHERE name = 'DASHARIYA KK NIMBA (SALEKASA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'DATTA K.K SONPURI (SALEKASA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'DESHMUKH K.K DONGARGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'DHERMENDRA MESHRAM (DM)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'DOLLY KRUSHY KENDRA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'DONGRE KRUSHI KENDRA SAKRITOLA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'DONODE KRUSHI KENDRA SAKRITOLA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'DURGA KK DAHEGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'DURGESH KK SONI (THANA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'EKANSH KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'A' WHERE name = 'FUNDE KK KALIMATI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'GAHANE KRUSHI KENDRA FUTADA,SADAK ARJUNI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GAIDHANE KK MUNDIPAR (GONDIA MIDC)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'GAIDHANE KK MUNDIPAR (TIRORA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GAIDHANE KRUSHI KENDR DEVATOLA(MANDOBAI)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'GAJANAN K.K PANDRI (SALEKASA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GAJANAN KRUSHI KENDRA RATNARA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GAJBHIYE KK SILEGAON (GOREGAON)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'GAJRA KRUSHI KENDRA KIKRIPAR';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Ganesh';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GANESH K.K.,NANVA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GANESH KK GOREGAON';
UPDATE stores SET dealer_category = 'A' WHERE name = 'GANESH KRUSHI KENDRA PANDHRABODI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'GAURAV KRUSHI KENDRA KHAJRI (SADAK ARJUNI)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'GAURISHANKAR KRUSHI KENDRA UMRI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GAUTAM K.K TAKRI (KALIMATI)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'GAYATRI K.K MUNDIPAR (MIDC, GONDIA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'GAYATRI KRUSHI CHICHTOLA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GAYATRI KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'A' WHERE name = 'GIRISH BOPCHE';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GIRJA KK SONARTOLA (SALEKASA)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'GONDIA FPC K.K KALPATHRI (GOREGAON)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'GOOGLE KK PARASWADA (TIRORA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'GOPAL KK KALPATHRI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Gurudeo Madavi';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GURUKRUPA KK TIRODA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'GURUKRUPA KRUSHI KENDRA THANA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GURVESH K.K DHAMANGAON (KIKRIPAR)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'GURVESH TRADER K.K DHAMANGAON (KIKRIPAR)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'HALDHAR KK AMGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'HARINKHEDE DM (BORI BHANEGAON), MP';
UPDATE stores SET dealer_category = 'D' WHERE name = 'HARINKHEDE KRUSHI KENDRA CHUTIYA';
UPDATE stores SET dealer_category = 'C' WHERE name = 'HARSH KK BUDI BANJARI (C.G)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'HATTIMARE K.K MOHGAON (KALIMATI)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'HIMALAYA KK GOREGAON';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'HINDUSTAN AGRO KUDWA (GONDIA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'IRUYAG KRUSHIKENDRA PARSODI SOUNDAD';
UPDATE stores SET dealer_category = 'A' WHERE name = 'JAI AMBE KRUSHI KENDRA SAWRI (RAWANWADI)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'JAI AMBE KRUSHI KENDRA SONI (GOREGAON)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'JAI BAJRANG KRUSHI KENDRA DAHEGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'JAI BHARAT K.K AMGAON';
UPDATE stores SET dealer_category = 'A' WHERE name = 'JAI BHOLE KRUSHI KENDRA KATANGTOLA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'JAI DURGA KK ADASI-TANDA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'JAI DURGA KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'C' WHERE name = 'JAI FULE KK LALBARRA (M.P)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'JAI KISAN KK TIRORA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'JAI KISAN KRUSHI KENDRA BANATHER';
UPDATE stores SET dealer_category = 'D' WHERE name = 'JAI LAXMI KRUSHI KENDRA PARASWADA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'JAI MAA SHARDA KK BIRSOLA';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'JAI MAHESH K.K ARJUNI (TIRORA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'JAI MATA DI KK PATHRI (KURHADI)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'JAITWAR KRUSHI KENDRA SALEKASA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'JAMBHURKAR KRUSHI KENDRA KAKODI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'JAY KISAN KRUSHI KENDRA KURHADI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'JHANGEL KRUSHI KENDRA DHIMRINKUA (C.G)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'JHANGEL KRUSHI KENDRA PAHLIMETA C.G';
UPDATE stores SET dealer_category = 'A' WHERE name = 'KABIR K.K DHAPEWADA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'KAMLESH KK SAHARWANI (GONDIA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'KANAK KK MAHAGAON (M.ARJUNI)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'KANHIYA KK MOHGAON BUJRUG (GOREGAON)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'KANHIYA KRUSHI KENDRA TIGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'KAPGATE KRUSHI KENDRA SADAK ARJUNI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Kartik';
UPDATE stores SET dealer_category = 'B' WHERE name = 'KARTIK KK KARANJA (GONDIA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'KASTKAR KK NAVEGAON - DHAPEWADA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'KASTKAR KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Kastura Bai';
UPDATE stores SET dealer_category = 'D' WHERE name = 'KATREJI PIPERTOLA (GANESH BISEN)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'KHANDELWAL KK AMBAGARH CHOWKI (CG)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'KHETIBADI KK TEMNHI (KATANGI)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'KISAN AGRO & KK DEORI';
UPDATE stores SET dealer_category = 'C' WHERE name = 'KISAN KRUSHI KENDRA GIDHADI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'KISAN KRUSHI KENDRA IRAIKALA (C.G)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'KISAN KRUSHI KENDRA JHALIA (KAWRABANDH)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Kishor Bhadmare';
UPDATE stores SET dealer_category = 'A' WHERE name = 'KRISHNA KK KAMARGAON (GOREGAON)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'KRUSHONATI SHETKARI PRO. CO. LTD. KAKODI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'KULDIP BORKAR SEONI (HATTA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'KURANJEKAR KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'LALIT RAHANGDALE AMGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'LALITA KK CHOPA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'LAVANYA KK ANJORA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'LILHARE K.K KAMTHA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MAA ADISHAKTI K.K MUNDIPAR';
UPDATE stores SET dealer_category = 'C' WHERE name = 'MAA BHAGWATI K.K BOPESAR (TIRORA)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'MAA DANTESHWARI KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'C' WHERE name = 'MAA GAYATRI KK GIROLA (KAMTHA)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'MAA GAYATRI KK MENDHA (TIRORA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'MAA SANTOSHI K.K PATHANTOLA (SALEKASA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MAA SHARDA KK NAVEGAON (KOTJAMURA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'MACHIRKE KK DAREKASA';
UPDATE stores SET dealer_category = 'C' WHERE name = 'MAHADEO K.K JHANZIA (GOREGAON)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'MAHAVIR KRUSHI KENDRA GONDUMRI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MAHENDRA KK HETITOLA (GUDMA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MAHESH KRUSHI KENDRA HIRDAMALI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MAHESHORE KRUSHI KENDRE KINNI (LANJI)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'MAMTA K.K DONGARGAON (DEORI)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MANGAL KK CHILATI (GOREGAON)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MANGAL KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MANGAL KRUSHI KENDRA CHILATI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MANKAR KRUSHI KENDRA PANCHWATI MHASGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MANKAR KRUSHI KENDRA, KHAMARI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MANOJ K.K (OWARA) DEORI';
UPDATE stores SET dealer_category = 'A' WHERE name = 'MARATHA KK KUNBITOLA SALEKASA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MATE KRUSHI KENDRA RAJEGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MATOSHRI KK KARDI (TIRODA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MATOSHRI KK KARTI (TIRODA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MATOSHRI KRUSHI KENDRA GOWARITOLA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MATOSHRI KRUSHI KENDRA GOWARITOLA-TEDHA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MATOSHRI KRUSHI KENDRA MURPAR (SA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MEERA KK GOREGAON';
UPDATE stores SET dealer_category = 'A' WHERE name = 'MENDHE K.K SUPLIPAR (KALIMATI)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MENDHE KK CHIDCHADBANDH';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'MENDHE KK IRRITOLA (KAMTHA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'MENDHE KRUSHI KENDRA TEDHA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MESHRAM KRUSHI KENDRA BORGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Modku Bhau';
UPDATE stores SET dealer_category = 'B' WHERE name = 'MOHARE KRUSHI KENDRA GOWARITOLA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MUKESH CHAUHAN KK SADAK ARJUNI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'MURKUTE KRUSHI KENDRA PALDONGRI (LANJI)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'NAGPURE KK BIRSI PHATA (TIRORA)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'NAGPURE KK MUNDIPAR (SALEKASA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'NAGPURE KK TIRORA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'NAGPURE KRUSHI KENDRA NAGRA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'NAGPURE KRUSHI KENDRA RAWANWADI';
UPDATE stores SET dealer_category = 'A' WHERE name = 'NAGPURE KRUSHI KENDRA TUMKHEDA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Naresh Driver';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'NAVDURGA KK GOREGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'NEW CHAUHAN KK ADASI';
UPDATE stores SET dealer_category = 'C' WHERE name = 'NIDHI KK BRAMHANTOLA SALEKASA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'NIKESH KRUSHI KENDRA KODSIVNI SDAK ARJNI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'NIRMAL KRUSHI KENDRA KIDANGIPAR';
UPDATE stores SET dealer_category = 'D' WHERE name = 'NITIN KK ASOLI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'NITIN KK ASOLI (GONDIA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'NIVESH KK CHICHGARH';
UPDATE stores SET dealer_category = 'D' WHERE name = 'OM HARI KK CHIDCHANDBANDH';
UPDATE stores SET dealer_category = 'D' WHERE name = 'OM SAI KRUSHI KENDRA BOTE';
UPDATE stores SET dealer_category = 'A' WHERE name = 'OM SAI KRUSHI KENDRA MUNDIPAR';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PANCHSHEEL KRUSHI KENDRA SONI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PARDESI K.K KAWRABANDH';
UPDATE stores SET dealer_category = 'A' WHERE name = 'PARMARJI FARM HOUSE GONDIA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'PARMATMA EK KK KAWRABANDH';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PARMATMA EK KRUSHI KENDRA SURTOLI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PATEL KK KHURSIPAR';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'PATEL KRUSHI CHIDHCHADBANDH';
UPDATE stores SET dealer_category = 'B' WHERE name = 'PATHODE KK GORTHA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'PATLE KK KHARA (KIRNAPUR M.P)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PATLE KRUSHI KENDRA BINORA (KIRNAPUR)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PATLE KRUSHI KENDRA CHILATI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PATLE KRUSHI KENDRA PATHERGAON';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'PATLE KRUSHI KENDRA SASAKARANTOLA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'PATLE KRUSHI KENDRA VARAD';
UPDATE stores SET dealer_category = 'B' WHERE name = 'PISSEY KRUSHI KENDRA GOREGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PONGEJHERA FARMER KURADI (GONDIA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'POWANKAR KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'POWANKAR KRUSHI KENDRA KALIMATI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'PRADHAN KK SADAK ARJUNI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'PRATIK KRUSHI KENDRA PADAMPUR';
UPDATE stores SET dealer_category = 'B' WHERE name = 'PREM KRUSHI KENDRA DEORI';
UPDATE stores SET dealer_category = 'A' WHERE name = 'PUJA KK KORCHI';
UPDATE stores SET dealer_category = 'A' WHERE name = 'PUJA KRUSHI KENDRA BHAJEPAR';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'RADHIKA KRUSHI KENDRA DEORI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'RAHANGDALE KRUSHI KENDRA SARKARTOLA';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'RAHUL KK CHIREKHANI (TIRORA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'RAHUL KK KIRNAPUR (PATALEJI )';
UPDATE stores SET dealer_category = 'B' WHERE name = 'RAJ KK HARDOLI (SAKRITOLA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'RAJESH JI BHAKTWARTI NANSARI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'RAJLAXMI KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'RATNAKAR KRUSHI KENDRA KAWRABANDH';
UPDATE stores SET dealer_category = 'D' WHERE name = 'RAUT KK SAKRITOLA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'RENUKA KK KHAMKHURA (A. MOREGAON)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'ROSHAN KK MAHAGAON (M. ARJUNI)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'RUPALI KK SONI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SAGAR KK FULCHUR';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SAHARE KRUSHI KENDRA MUNDIPAR (NANSARI)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SAI BABA KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SAI KK CHURDI (TIRORA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SAI RAM KK MAHALGAON (TIRORA)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'SAIBABA KRUSHI KENDRA DASGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SAMYAK KRUSHI KENDRA KINNI DASGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Sanjay';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SANJAY HARINKHEDE KK ACC.';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SANJAYJI THAKUR CHILATI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SANJEEVNI KRUSHI KENDRA THAKURTOLA C.G';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SANTOSHI KRUSHI KENDRA PINDKEPAR';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'SARASWATI KRUSHI KENDRA RAWANWADI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Sarita Bai';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SATYAM KRUSHI KENDRA NARMADA C.G';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SAWJI KK RAJEGAON';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SEWA KRUSHI KENDRA BAMNI SALEKASA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHAKTI KRUSHI KENDRA PANJRA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SHARDA KRUSHI KENDRA KATANGI (NAGRA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHENDE KRUSHI KENDRA BHOSA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHETKARI KK BHADUTOLA (KARANJA-GONDIA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHETKARI KK DHEMARTOLI (GONDIA)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SHETKARI KRUSHI KENDRA SOUNDAD';
UPDATE stores SET dealer_category = 'C' WHERE name = 'SHETKARI KRUSHI KENDRA THANA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SHETKARI RAJA KK BOREGAON (KURHADI)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'SHITAL KRUSHI KENDRA GANUTOLA CHICHGARH';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHIV KRUSHI KENDRA BHORAMPUR (C.G)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHIV KRUSHI KENDRA CHIRAMANTOLA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHIVAM KK SUKDI';
UPDATE stores SET dealer_category = 'C' WHERE name = 'SHIVAM KRUSHI KENDRA TILLI MOHGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHIVSHAKTI SEWA KK KOKNA NAVEGAON ROAD';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SHRADDHA KK GHATTEMNI (KAMTHA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SHRAWAN KK DEVUTOLA/ PANCHWATI';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SHRI GANESH KK KHOLGADH';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SHRI KALANTRI FARM HOUSE POULDOWNA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SHRI KK JHALIA (SALEKASA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHRI KK SAKRITOLA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SHRI KRISHNA KRUSHI KENDRA MUNDIPAR';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SHRI SAI KK MUNDIPAR (SALEKASA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHRI SAI KK SALEKASA ROAD AMGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SHRI SAI KK TEMHANI (NAGRA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SHRI TRISHA KK TELANKHEDI (GOREGAON)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'SHUBHAM KK GOND MOHADI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHUBHAM KK GOREGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHUBHAM KK KHURSIPAR';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHUBHAM PATLE.CHICHGAON ABC';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SHUBHLAKSHMI K.K SARKARTOLA';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SHYAM KK DAUNEWADA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHYAMA SHYAM KK BADEGAON (TIRORA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SHYAMBABA KRUSHI KENDRA THANA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SINGANDHUPE KK MAHARITOLA';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Sona Bai';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SONWANE KRUSHI KENDRA KIKRIPAR';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SUKHDEO PATLE  (DM)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Sukhdeo Yetre';
UPDATE stores SET dealer_category = 'D' WHERE name = 'SULAKHE KRUSHI KENDRA PANDHRABODI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'SUMAN KK GOREGAON';
UPDATE stores SET dealer_category = 'A' WHERE name = 'SUMAN KK KATTIPAR';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Suresh ';
UPDATE stores SET dealer_category = 'B' WHERE name = 'TAJ KRUSHI KENDRA KIRNAPUR (M.P)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'TAKSH KK BHADANGA (GOREGAON)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'TANISHQ K.K MUNDIPAR (GOREGAON)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'TEMBHRE KK KARTI (TIRODA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'TEMBHRE KK SONI';
UPDATE stores SET dealer_category = 'D' WHERE name = 'TEMBHREJI KHURSIPAR (PATEL SAHEB)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'THAKRE KK BORI, MAHAGAON (A. MOREGAON)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'THAKUR K.K SONEKHARI (SALEKASA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'TOMAR KK BADEGAON (KIRNAPUR)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'TRIPATHI KK GENDA TOLA (C.G)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'TRIVENI KK MAHAGAON (A. MOREGAON)';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'TUSHAR K.K DANDEGAON (GONDIA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'UNNATI KRUSHI KENDRA ASOLI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'UPRADE KK PANGAON (SALEKASA)';
UPDATE stores SET dealer_category = 'C' WHERE name = 'UPRADE KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'D' WHERE name = 'UPRADE KRUSHI KENDRA MUNDIPAR';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'UPRADE KRUSHI KENDRA PANGAON (SALEKASA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'URJA KRUSHI KENDRA AMGAON';
UPDATE stores SET dealer_category = 'B' WHERE name = 'Urmila Bai';
UPDATE stores SET dealer_category = 'A+' WHERE name = 'VAINGANGA KK MUNDIKOTA (TIRORA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'VAIRAGADE KRUSHI KENDRA NANSARI';
UPDATE stores SET dealer_category = 'B' WHERE name = 'VANJARI K.K KARANJI (KALIMATI)';
UPDATE stores SET dealer_category = 'A' WHERE name = 'VIDHARBH KK AMGAON';
UPDATE stores SET dealer_category = 'A' WHERE name = 'VIJAY K.K NANVAH (SALEKASA)';
UPDATE stores SET dealer_category = 'B' WHERE name = 'VIKTU BABA K.K KATTIPAR';
UPDATE stores SET dealer_category = 'D' WHERE name = 'VIMAL KRUSHI KENDRA KATI';
UPDATE stores SET dealer_category = 'A' WHERE name = 'YASH K.K SITEPAR';
UPDATE stores SET dealer_category = 'A' WHERE name = 'YEDE KRUSHI KENDRA GATRA';
UPDATE stores SET dealer_category = 'D' WHERE name = 'YEWALKAR KRUSHI KENDRA SOUNDAD';
UPDATE stores SET dealer_category = 'D' WHERE name = 'YOGESH SHENDE (ASOLI) DM';
UPDATE stores SET dealer_category = 'B' WHERE name = 'YUGAL KK GARDA (SUKDI TIRORA)';
UPDATE stores SET dealer_category = 'D' WHERE name = 'YUVRAJJI VYAPARI BAJARTOLA (LANJI)';
